spring:
  application:
    name: gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    account-service:
      path: /vat/**
      serviceId: invoice-service
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 4000
