server:
  port: 1111
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0

spring:
  application:
    name: registry